dist: trusty
language: crystal
jdk:
  - oraclejdk8
node_js:
  - "6"

addons:
  apt:
    packages:
      - python-scipy
      - python-yaml

git:
  submodules: false

# env:
#   - LANG=crystal
#   - LANG=java
#   - LANG=js
#   - LANG=ruby
#   - LANG=som
#   - LANG=somns
#   - LANG=pharo

matrix:
  include:
    - env: LANG=pharo
      language: smalltalk
      smalltalk: Pharo-5.0
    - env: LANG=squeak
      sudo: required
      language: smalltalk
      smalltalk: Squeak-5.1
    - env: LANG=rsqueak
      sudo: required
      language: smalltalk
      smalltalk: Squeak-5.1
      addons:
        apt:
          packages:
            - python-scipy
            - python-yaml
            - libsdl2-2.0-0
            - libffi6

install:
  - pip install --user ReBench
  - if [ "$LANG" = "ruby" ]; then rvm use 2.3.1 --install --binary --fuzzy && gem install rubocop; fi
  - if [ "$LANG" = "js" ]; then nvm install 6 && npm install jshint; fi
  - if [ "$LANG" = "som" ] || [ "$LANG" = "somns" ]; then jdk_switcher use oraclejdk8; fi

script:
  - implementations/build-$LANG.sh && rebench -q test.conf test-$LANG
  - implementations/build-$LANG.sh style
